apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
commonAnnotations:
  note: This is a dev environment
patches:
- path: patch.yaml
labels:
- includeSelectors: true
  pairs:
    variant: dev
